### ISSUE TITLE
Font size in gamelists.

### ISSUE THREAD

**Issue by Fredoias** [mluizvitor/es-theme-elementerial#20]
Is there a way to reduce the font size for the gamelists? I have tried to do it myself but I must be missing something. Beautiful Theme.  
![test](https://user-images.githubusercontent.com/72955779/216745568-7432dafb-dbf2-48c3-8848-3526525e28d8.jpg)

**Comment by mluizvitor** [comment]
Hi fredoias. I recently refactored the theme and updated a few things, including standardized sizes (fonts, spacing, etc) across devices. Please check the update and let me know if this helped you.

**Comment by Fredoias** [comment]
Thank you very much. I will check it out and let you know. I should have let you know what device I was running it on. Anbernic Rg353v.

**Comment by Fredoias** [comment]
Fonts definitely look better now. Thanks. 
![20230226_063052](https://user-images.githubusercontent.com/72955779/221407881-772fdd2e-f074-4d0e-92ad-0339c878559b.jpg)

**Comment by Fredoias** [comment]
Looks like something is up with Daphne. It was working before. 
![20230226_064015](https://user-images.githubusercontent.com/72955779/221408380-18f9a420-0c0c-4a0b-b8b4-15d7ae7526c0.jpg)

**Comment by Fredoias** [comment]
![20230226_064027](https://user-images.githubusercontent.com/72955779/221408394-5a539082-3f80-4fc6-a452-9bb19c6c9d7a.jpg)

**Comment by mluizvitor** [comment]
I'll look into it. Is there any other systems lacking logo or backgrounds on your OS?

**Comment by mluizvitor** [comment]
I've restored Daphne assets (13ad6ba). You can now update in your device.
In case you found some unsupported system, open a new issue.
Thank you for your feedback.
